lab7/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^$', views.ExampleView.as_view()),
    url(r'^lessons/', views.LessonsView.as_view(), name='lessons'),
    url(r'^lesson/(?P<id>\d+)', views.LessonView.as_view(), name='lesson_url'),
    url(r'^user/(?P<id>\d+)/teach/(?P<lid>\d+)$', views.teach, name='teach'),
    url(r'^signup/', views.registration, name='signup'),
    url(r'^login/', views.authorization, name='login'),
    url(r'^logout/', views.exit, name='logout'),
    url(r'^new_lesson/', views.new_lesson, name='new_lesson'),
    url(r'^success/', views.SuccessView.as_view(), name='success'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

lab7mary/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('lab7.urls')),
]

lab7/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.

class MyUser(AbstractUser):
    teachs = models.ForeignKey('Lesson',related_name='teachers', on_delete=models.CASCADE, null=True)

class Lesson(models.Model):
	name = models.CharField(max_length=30, verbose_name='Курс')
	description = models.CharField(max_length=255, verbose_name='Описание курса')
	datetime = models.DateTimeField(auto_now=True)
	image = models.ImageField(upload_to = 'lessons_images/', default = 'lessons_images/None/no-image.jpg', verbose_name='Изображение')
	user_posted = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Преподаватель', related_name='lessons', null=True)
    
	def __str__(self):
		return self.name

lab7/forms.py
#__author__ = 'Work'
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from lab7.models import Lesson

class LessonForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea, label='Описание курса')
    image = forms.ImageField(required=False, label='Изображение')
    class Meta:
        model = Lesson
        exclude = ('user_posted',)
    
    def save(self):
        user_model = get_user_model()
        les_pic = self.cleaned_data['image']
        print(les_pic)
        print(self.cleaned_data)
        if not les_pic:
            les_pic = 'lessons_images/None/no-image.jpg'
        lesson = Lesson.objects.create(name=self.cleaned_data['name'],
                                        description=self.cleaned_data['description'],
                                        image = les_pic,
                                        )
        return lesson


class LoginForm(forms.Form):
    login = forms.CharField(label='Логин')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    login = forms.CharField(label='Логин', min_length=5)
    password = forms.CharField(label='Пароль', min_length=8, widget=forms.PasswordInput)
    repeat_password = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    email = forms.CharField(label='Адрес электронной Почты')
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')

    def clean_login(self):
        user_model = get_user_model()
        login = self.cleaned_data['login']
        if user_model.objects.filter(username=login):
            raise ValidationError('Этот login уже занят')
        return login

    def clean_email(self):
        user_model = get_user_model()
        email = self.cleaned_data['email']
        validate_email( self.cleaned_data['email'])
        if user_model.objects.filter(email=email):
            raise ValidationError('Этот email уже зарегистрирован')
        return self.cleaned_data['email']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        if self.cleaned_data.get('password') and self.cleaned_data.get('repeat_password'):
            if self.cleaned_data['password'] != self.cleaned_data['repeat_password']:
                raise ValidationError('Пароли не совпадают')
        return cleaned_data

    def save(self):
        user_model = get_user_model()
        user = user_model.objects.create_user(username=self.cleaned_data['login'],
                                        email=self.cleaned_data['email'],
                                        password=self.cleaned_data['password'],
                                        first_name=self.cleaned_data['first_name'],
                                        last_name=self.cleaned_data['last_name'],
                                        )
        return user

lab7/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from lab7.models import *
from lab7.forms import *
from django import forms
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate,logout
from django.contrib import auth

# Create your views here.

class ExampleView(View):
    def get(self, request):
        return render(request, 'base.html')

class SuccessView(View):
    def get(self, request):
        return render(request, 'success.html')

class LessonsView(ListView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'lessons.html'
    paginate_by = 5
    
    def get_queryset(self):
        qs = Lesson.objects.all().order_by('id')
        return qs

class LessonView(View):
    def get(self, request, id):
        data = Lesson.objects.get(id__exact=id)
        return render(request, 'lesson.html', {'lesson':data})

def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/lessons')
        return render(request, 'signup.html', {'form': form})
    else:
        form = RegistrationForm()
    return render(request, 'signup.html', {'form': form})

def authorization(request):
    redirect_url = '/lessons'
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = auth.authenticate(username=form.cleaned_data['login'],
                                     password=form.cleaned_data['password'])
            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect(redirect_url)
            else:
                form.add_error(None, 'Wrong login or password')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form':form, 'continue': redirect_url})

@login_required
def exit(request):
    logout(request)
    return render(request, 'logout.html')
    
@login_required
def new_lesson(request):
    instance = Lesson(user_posted=request.user)
    if request.method == 'POST':
        form = LessonForm(request.POST,request.FILES)
        if form.is_valid():
            lesson = form.save()
            lesson.user_posted = request.user
            print(lesson.user_posted.id)
            lesson.save()
            return redirect(reverse('lesson_url', args=(lesson.id,)))
        return render(request, 'new_lesson.html', {'form': form})
    else:
        form = LessonForm()
    return render(request, 'new_lesson.html', {'form': form})

@login_required
def teach(request, id, lid):
    teacher = MyUser.objects.filter(id=id)[0]
    lesson = Lesson.objects.filter(id=lid)[0]
    if teacher in lesson.teachers.all():
        return HttpResponse('Вы уже ведёте этот урок и наверняка балуетесь с адресной строкой')
    lesson.teachers.add(teacher)
    return HttpResponse('Теперь вы ведёте {}'.format(
       lesson.name
))

lab7/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <title>{% block title %}Тестовый вывод{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">РЕПЕТИТОРСТВО</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Базовый класс</a></li>
        <li><a href="{% url 'lessons' %}">Уроки</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'new_lesson' %}">Новый урок</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><div style="padding-top:15px"><i><b>Здраствуйте, {{ user.get_short_name }}</b></i></div></li>
            <li><a href="{% url 'logout' %}">Выйти из {{ user.get_username }}</a></li>
        {% else %}
            <li><div style="padding-top:15px"><i><b>Вы вошли как Гость</b></i></div></li>
            <li><a href="{% url 'signup' %}">Зарегистрироваться</a></li>
            <li><a href="{% url 'login' %}">Войти</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <div>
        {% block body %}Redefined by spawnlings{% endblock %}
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

lab7/templates/lesson.html
{% extends 'base.html' %}

{% block title %}Урок №{{ lesson.id }}{% endblock %}

{% block body %}
<img src={{ lesson.image.url }} style="max-height:250px;margin-left:50px"/>
<h1>Урок №{{ lesson.id }} &ndash; {{ lesson.name }}</h1>
<p>{{ lesson.description }}</p>
<p>Урок создан пользователем {{ lesson.user_posted }}</p>
<p>Урок ведут учителя:</p>
    <ul class="list-group">
        {% for teacher in lesson.teachers.all %}
            <li class="list-group-item">{{ teacher }}</a></li>
        {% empty %}
            <li class="list-group-item disabled">Ещё никто не вызвался вести занятие</li>
        {% endfor %}
    </ul>
{% if user.is_authenticated %}
    {% if user not in lesson.teachers.all %}
    <form action="{% url 'teach' user.id lesson.id %}">
        <input type="submit" class="btn btn-primary" value="Стать преподавателем!" />
    </form>
    {% endif %}
{% endif %}
{% endblock %}

lab7/templates/lessons.html
{% extends 'base.html' %}

{% block title %}Уроки{% endblock %}

{% block body %}
    <ul class="list-group">
        {% for lesson in lessons %}
            <li class="list-group-item"><a href="{% url 'lesson_url' lesson.id %}">{{lesson.id}} &ndash; {{ lesson.name }}</a></li>
        {% empty %}
            <li class="list-group-item disabled">empty list</li>
        {% endfor %}
    </ul>
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

lab7/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block body %}

{{ form.non_field_errors }}
<form action="{% url 'login' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {%  for i in form %}
                    <div class="form-group">
                        <label class="col-sm-2">{{ i.label }}</label>
                        <div class="col-sm-10">
                            <div>
                                {{ i }}
                            </div>

                        </div>
                    </div>
                    {% endfor %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" value="Войти" class="btn btn-default"/>
                        </div>
                    </div>
</form>
{% endblock %}

lab7/templates/logon.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block body %}

<form action="{% url 'signupNOFORM' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                        <div class="form-group">
        <label class="col-sm-4">Логин</label>
        <div class="col-sm-8">
            <div>
                <input id="id_login" minlength="5" name="username" type="text" required />
            </div>
            <div>
                
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-4">Пароль</label>
        <div class="col-sm-8">
            <div>
                <input id="id_password" minlength="8" name="password" type="password" required />
            </div>
            <div>
                
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-4">Повторите пароль</label>
        <div class="col-sm-8">
            <div>
                <input id="id_repeat_password" name="password2" type="password" required />
            </div>
            <div>
                
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-4">Адрес электронной Почты</label>
        <div class="col-sm-8">
            <div>
                <input id="id_email" name="email" type="text" required />
            </div>
            <div>
                
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-4">Имя</label>
        <div class="col-sm-8">
            <div>
                <input id="id_first_name" name="first_name" type="text" required />
            </div>
            <div>
                
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-4">Фамилия</label>
        <div class="col-sm-8">
            <div>
                <input id="id_last_name" name="last_name" type="text" required />
            </div>
            <div>
                
            </div>
        </div>
    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" value="Зарегистрироваться" class="btn btn-default"/>
                        </div>
                    </div>
</form>
{% endblock %}

lab7/templates/logout.html
{% extends 'base.html' %}

{% block title %}Выход{% endblock %}

{% block body %}
<p>Выход произошёл успешно.</p>
{% endblock %}

lab7/templates/new_lesson.html
{% extends 'base.html' %}

{% block title %}Новый урок{% endblock %}

{% block body %}

{{ form.non_field_errors }}
<form action="{% url 'new_lesson' %}" method="post" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    {% for i in form %}
    <div class="form-group">
        <label class="col-sm-2">{{ i.label }}</label>
        <div class="col-sm-4">
            <div>
                {{ i }}
            </div>
            <div>
                {{ i.errors }}
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-4">
            <input type="submit" value="Разместить занятие" class="btn btn-default"/>
        </div>
    </div>
</form>
{% endblock %}

lab7/templates/signup.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block body %}

{{ form.non_field_errors }}
<form action="{% url 'signup' %}" method="post" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    {%  for i in form %}
    <div class="form-group">
        <label class="col-sm-4">{{ i.label }}</label>
        <div class="col-sm-8">
            <div>
                {{ i }}
            </div>
            <div>
                {{ i.errors }}
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
            <input type="submit" value="Зарегистрировать меня" class="btn btn-default"/>
        </div>
    </div>
</form>
{% endblock %}

lab7/templates/success.html
{% extends 'base.html' %}

{% block title %}АЛЛИЛУЯ!{% endblock %}

{% block body %}

{% if user.is_authenticated %}
<p>Пользователь {{ user.get_username }} успешно вошёл :)</p>
{% else %}
<p>Авторизации не было</p>
{% endif %}
{% endblock %}